class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Sarkari Mitra',
      'ask_anything': 'Ask Sarkari Mitra anything...',
      'welcome': 'Welcome',
      'recommended_schemes': 'Recommended schemes for',
      'in': 'in',
      'loading_recommendations': 'Loading your AI recommendations...',
      'no_schemes': 'No personalized schemes found. Here are all available schemes.',
      'recommended_for_you': 'Recommended For You',
      'trending_schemes': 'Trending Schemes',
      'popular_in': 'Popular in',
      'highly_eligible': 'Highly Eligible',
      'match': 'Match',
      'apply_now': 'Apply Now',
      'all_schemes': 'All Schemes',
      'home': 'Home',
      'categories': 'Categories',
      'profile': 'Profile',
      'my_profile': 'My Profile',
      'edit_profile': 'Edit Profile',
    },
    'hi': {
      'app_title': 'सरकारी मित्र',
      'ask_anything': 'सरकारी मित्र से कुछ भी पूछें...',
      'welcome': 'नमस्ते',
      'recommended_schemes': 'के लिए अनुशंसित योजनाएं',
      'in': 'में',
      'loading_recommendations': 'आपकी AI अनुशंसाएं लोड हो रही हैं...',
      'no_schemes': 'कोई व्यक्तिगत योजना नहीं मिली। यहाँ सभी उपलब्ध योजनाएं हैं।',
      'recommended_for_you': 'आपके लिए अनुशंसित',
      'trending_schemes': 'ट्रेंडिंग योजनाएं',
      'popular_in': 'में लोकप्रिय',
      'highly_eligible': 'अत्यधिक योग्य',
      'match': 'मैच',
      'apply_now': 'अभी आवेदन करें',
      'all_schemes': 'सभी योजनाएं',
      'home': 'होम',
      'categories': 'श्रेणियाँ',
      'profile': 'प्रोफ़ाइल',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
    },
    'kn': {
      'app_title': 'ಸರ್ಕಾರಿ ಮಿತ್ರ',
      'ask_anything': 'ಸರ್ಕಾರಿ ಮಿತ್ರರನ್ನು ಏನನ್ನಾದರೂ ಕೇಳಿ...',
      'welcome': 'ಸ್ವಾಗತ',
      'recommended_schemes': 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಯೋಜನೆಗಳು',
      'in': 'ನಲ್ಲಿ',
      'loading_recommendations': 'ನಿಮ್ಮ AI ಶಿಫಾರಸುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'no_schemes': 'ಯಾವುದೇ ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಲಭ್ಯವಿರುವ ಎಲ್ಲಾ ಯೋಜನೆಗಳು ಇಲ್ಲಿವೆ.',
      'recommended_for_you': 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
      'trending_schemes': 'ಟ್ರೆಂಡಿಂಗ್ ಯೋಜನೆಗಳು',
      'popular_in': 'ಜನಪ್ರಿಯ',
      'highly_eligible': 'ಹೆಚ್ಚು ಅರ್ಹರು',
      'match': 'ಹೊಂದಾಣಿಕೆ',
      'apply_now': 'ಈಗ ಅನ್ವಯಿಸು',
      'all_schemes': 'ಎಲ್ಲಾ ಯೋಜನೆಗಳು',
      'home': 'ಮುಖಪುಟ',
      'categories': 'ವರ್ಗಗಳು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    },
  };

  static String get(String locale, String key) {
    return _translations[locale]?[key] ?? _translations['en']![key] ?? key;
  }
}
